name = "transobras"
main = "src/worker/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
EMAIL_RECIPIENT = "gestores@transobra.com.br"
EMAIL_FROM = "TransObra <onboarding@resend.dev>"

[assets]
directory = "dist"
binding = "ASSETS"
